version: 0.0
os: linux
files:
  - source: paws-pets-0.0.1-SNAPSHOT.jar
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/java/stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/java/start.sh
      timeout: 10
      runas: ec2-user
  ValidateService:
    - location: scripts/java/validate.sh
      timeout: 10
      runas: ec2-user